# Generated by Django 3.2.12 on 2022-02-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(choices=[('div', 'Div'), ('section', 'Section'), ('h1', 'Header 1'), ('h2', 'Header 2'), ('h3', 'Header 3'), ('h4', 'Header 4'), ('h5', 'Header 5'), ('h6', 'Header 5')], default='div', max_length=32, verbose_name='Tag'),
        ),
    ]
